"""
Install and uninstall rtt context into agent config files.

Each supported agent reads a specific file at session start. rtt injects
an instruction into that file telling the agent to read the skeleton first,
before touching any source files.

The skeleton is written to .rtt/context.txt in the repo root. The injected
section is wrapped in markers so it can be cleanly removed by uninstall.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# ── marker strings ────────────────────────────────────────────────────────────

_START = "<!-- rtt:start -->"
_END   = "<!-- rtt:end -->"


# ── platform registry ─────────────────────────────────────────────────────────

@dataclass
class Platform:
    name: str
    label: str               # human-readable name
    config_path: str         # relative to repo root
    always_create: bool      # create the file even if it doesn't exist
    format: str              # "markdown" | "mdc"


PLATFORMS: list[Platform] = [
    Platform("claude",   "Claude Code",         "CLAUDE.md",                           True,  "markdown"),
    Platform("cursor",   "Cursor",              ".cursor/rules/rtt.mdc",               True,  "mdc"),
    Platform("windsurf", "Windsurf",            ".windsurfrules",                      True,  "markdown"),
    Platform("codex",    "Codex / OpenAI",      "AGENTS.md",                           True,  "markdown"),
    Platform("copilot",  "GitHub Copilot",      ".github/copilot-instructions.md",     True,  "markdown"),
    Platform("kiro",     "Kiro",                ".kiro/steering/rtt.md",               True,  "markdown"),
    Platform("gemini",   "Gemini CLI",          "GEMINI.md",                           True,  "markdown"),
    Platform("aider",    "Aider",               ".aider/prompts/conventions.md",       True,  "markdown"),
    Platform("zed",      "Zed",                 ".rules",                              True,  "markdown"),
]

PLATFORM_BY_NAME: dict[str, Platform] = {p.name: p for p in PLATFORMS}


# ── instruction text ──────────────────────────────────────────────────────────

def _instruction_block(
    context_path: str,
    compressed_tokens: int,
    raw_tokens: int,
    reduction: float,
    fmt: str,
) -> str:
    body = (
        f"This repository has been indexed with rtt (reducethemtokens).\n"
        f"A complete structural skeleton is stored at `{context_path}`.\n\n"
        f"**At the start of every session, read `{context_path}` before opening any source files.**\n"
        f"It covers the full API surface of this codebase — every file's imports, function\n"
        f"signatures, class hierarchies, and method lists — in {compressed_tokens:,} tokens\n"
        f"(down from {raw_tokens:,} raw tokens, {reduction:.0f}% smaller).\n\n"
        f"Use `{context_path}` as your primary reference for code structure. Only open\n"
        f"individual source files when you need to read or edit specific implementation details.\n"
        f"When the codebase changes, regenerate with: rtt install"
    )

    if fmt == "mdc":
        content = (
            "---\n"
            "description: Repository structure index — generated by rtt\n"
            "alwaysApply: true\n"
            "---\n\n"
            + body
        )
    else:
        content = "## rtt — repository context\n\n" + body

    return f"{_START}\n{content}\n{_END}\n"


# ── read / write helpers ──────────────────────────────────────────────────────

def _has_rtt_section(text: str) -> bool:
    return _START in text


def _replace_rtt_section(text: str, new_block: str) -> str:
    pattern = re.compile(
        re.escape(_START) + r".*?" + re.escape(_END) + r"\n?",
        re.DOTALL,
    )
    return pattern.sub(new_block, text)


def _remove_rtt_section(text: str) -> str:
    pattern = re.compile(
        re.escape(_START) + r".*?" + re.escape(_END) + r"\n?",
        re.DOTALL,
    )
    return pattern.sub("", text).rstrip("\n") + ("\n" if text.endswith("\n") else "")


# ── install / uninstall ───────────────────────────────────────────────────────

@dataclass
class InstallResult:
    platform: str
    config_file: str
    action: str     # "created" | "updated" | "skipped"
    note: str = ""


def install(
    repo_root: str,
    platform_names: Optional[list[str]],
    compressed_tokens: int,
    raw_tokens: int,
    reduction: float,
    force: bool = False,
) -> list[InstallResult]:
    root = Path(repo_root)
    context_rel = ".rtt/context.txt"
    results: list[InstallResult] = []

    platforms = (
        [PLATFORM_BY_NAME[n] for n in platform_names if n in PLATFORM_BY_NAME]
        if platform_names
        else PLATFORMS
    )

    for p in platforms:
        config = root / p.config_path
        block  = _instruction_block(context_rel, compressed_tokens, raw_tokens, reduction, p.format)

        if config.exists():
            existing = config.read_text(encoding="utf-8")
            if _has_rtt_section(existing) and not force:
                results.append(InstallResult(
                    platform=p.name,
                    config_file=p.config_path,
                    action="skipped",
                    note="already installed (use --force to overwrite)",
                ))
                continue
            new_text = _replace_rtt_section(existing, block) if _has_rtt_section(existing) else existing.rstrip("\n") + "\n\n" + block
            config.write_text(new_text, encoding="utf-8")
            results.append(InstallResult(platform=p.name, config_file=p.config_path, action="updated"))
        else:
            config.parent.mkdir(parents=True, exist_ok=True)
            config.write_text(block, encoding="utf-8")
            results.append(InstallResult(platform=p.name, config_file=p.config_path, action="created"))

    return results


def uninstall(
    repo_root: str,
    platform_names: Optional[list[str]],
    remove_skeleton: bool = False,
) -> list[InstallResult]:
    root = Path(repo_root)
    results: list[InstallResult] = []

    platforms = (
        [PLATFORM_BY_NAME[n] for n in platform_names if n in PLATFORM_BY_NAME]
        if platform_names
        else PLATFORMS
    )

    for p in platforms:
        config = root / p.config_path
        if not config.exists():
            continue
        text = config.read_text(encoding="utf-8")
        if not _has_rtt_section(text):
            continue
        cleaned = _remove_rtt_section(text)
        if cleaned.strip():
            config.write_text(cleaned, encoding="utf-8")
        else:
            config.unlink()
        results.append(InstallResult(platform=p.name, config_file=p.config_path, action="updated"))

    if remove_skeleton:
        skel = root / ".rtt" / "context.txt"
        if skel.exists():
            skel.unlink()

    return results
