"""
Install and uninstall rtt context into agent config files.

Each supported agent reads a specific file at session start. rtt injects
an instruction into that file telling the agent to read the skeleton first,
before touching any source files.

The skeleton is written to .rtt/context.txt in the repo root. The injected
section is wrapped in markers so it can be cleanly removed by uninstall.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# ── marker strings ────────────────────────────────────────────────────────────

_START = "<!-- rtt:start -->"
_END   = "<!-- rtt:end -->"


# ── platform registry ─────────────────────────────────────────────────────────

@dataclass
class Platform:
    name: str
    label: str               # human-readable name
    config_path: str         # relative to repo root
    always_create: bool      # create the file even if it doesn't exist
    format: str              # "markdown" | "mdc"
    detect_signals: list[str] = field(default_factory=list)  # paths that indicate this platform is in use


PLATFORMS: list[Platform] = [
    Platform("claude",   "Claude Code",         "CLAUDE.md",                           True,  "markdown",
             ["CLAUDE.md", ".claude"]),
    Platform("cursor",   "Cursor",              ".cursor/rules/rtt.mdc",               True,  "mdc",
             [".cursor"]),
    Platform("windsurf", "Windsurf",            ".windsurfrules",                      True,  "markdown",
             [".windsurfrules", ".windsurf"]),
    Platform("codex",    "Codex / OpenAI",      "AGENTS.md",                           True,  "markdown",
             ["AGENTS.md"]),
    Platform("copilot",  "GitHub Copilot",      ".github/copilot-instructions.md",     True,  "markdown",
             [".github"]),
    Platform("kiro",     "Kiro",                ".kiro/steering/rtt.md",               True,  "markdown",
             [".kiro"]),
    Platform("gemini",   "Gemini CLI",          "GEMINI.md",                           True,  "markdown",
             ["GEMINI.md"]),
    Platform("aider",    "Aider",               ".aider/prompts/conventions.md",       True,  "markdown",
             [".aider"]),
    Platform("continue", "Continue.dev",        ".continue/rules/rtt.md",              True,  "markdown",
             [".continue"]),
    Platform("zed",      "Zed",                 ".rules",                              True,  "markdown",
             [".zed", ".rules"]),
]

PLATFORM_BY_NAME: dict[str, Platform] = {p.name: p for p in PLATFORMS}


def detect_platforms(repo_root: str) -> list[str]:
    """Detect which AI agent platforms are in use based on config files/dirs.

    Returns a list of platform names that were detected. If nothing is
    detected, returns an empty list (caller should fall back to all platforms).
    """
    root = Path(repo_root)
    detected: list[str] = []

    for p in PLATFORMS:
        for signal in p.detect_signals:
            if (root / signal).exists():
                detected.append(p.name)
                break

    return detected


# ── instruction text ──────────────────────────────────────────────────────────

def _instruction_block(
    context_path: str,
    compressed_tokens: int,
    raw_tokens: int,
    reduction: float,
    fmt: str,
) -> str:
    body = (
        f"## Repository index (rtt)\n\n"
        f"A structural skeleton of this codebase is at `{context_path}`.\n"
        f"It was generated by [rtt](https://github.com/yttrium400/reducethemtokens) "
        f"and contains every file's imports, function signatures, class hierarchies, and "
        f"method lists in {compressed_tokens:,} tokens "
        f"({reduction:.0f}% smaller than the {raw_tokens:,}-token raw source).\n\n"
        f"**Read `{context_path}` at the start of this session before making any tool calls.**\n\n"
        f"Use the index as your first lookup step:\n\n"
        f"- Before reading any source file, check the index to see if it already answers "
        f"your question (signatures, return types, parameters, class members, imports)\n"
        f"- Use it to identify which specific files are relevant before opening them - "
        f"do not scan files speculatively to understand structure\n"
        f"- When asked where something is defined, which methods a class has, or what a "
        f"function signature looks like, answer from the index directly\n\n"
        f"Only open a source file when you need implementation details the index does not "
        f"contain: function bodies, logic, comments, or the actual code to edit.\n\n"
        f"The first line of `{context_path}` shows when it was generated and how many "
        f"files it covers. If it looks outdated relative to recent changes, or if the "
        f"file is missing entirely, tell the user to run `rtt update` before continuing."
    )

    if fmt == "mdc":
        content = (
            "---\n"
            "description: Repository structure index - generated by rtt. Read this first.\n"
            "alwaysApply: true\n"
            "---\n\n"
            + body
        )
    else:
        content = body

    return f"{_START}\n{content}\n{_END}\n"


# ── read / write helpers ──────────────────────────────────────────────────────

def _has_rtt_section(text: str) -> bool:
    return _START in text


def _replace_rtt_section(text: str, new_block: str) -> str:
    pattern = re.compile(
        re.escape(_START) + r".*?" + re.escape(_END) + r"\n?",
        re.DOTALL,
    )
    return pattern.sub(new_block, text)


def _remove_rtt_section(text: str) -> str:
    pattern = re.compile(
        re.escape(_START) + r".*?" + re.escape(_END) + r"\n?",
        re.DOTALL,
    )
    return pattern.sub("", text).rstrip("\n") + ("\n" if text.endswith("\n") else "")


# ── install / uninstall ───────────────────────────────────────────────────────

@dataclass
class InstallResult:
    platform: str
    config_file: str
    action: str     # "created" | "updated" | "skipped"
    note: str = ""


def install(
    repo_root: str,
    platform_names: Optional[list[str]],
    compressed_tokens: int,
    raw_tokens: int,
    reduction: float,
    force: bool = False,
) -> list[InstallResult]:
    root = Path(repo_root)
    context_rel = ".rtt/context.txt"
    results: list[InstallResult] = []

    platforms = (
        [PLATFORM_BY_NAME[n] for n in platform_names if n in PLATFORM_BY_NAME]
        if platform_names
        else PLATFORMS
    )

    for p in platforms:
        config = root / p.config_path
        block  = _instruction_block(context_rel, compressed_tokens, raw_tokens, reduction, p.format)

        if config.exists():
            existing = config.read_text(encoding="utf-8")
            if _has_rtt_section(existing) and not force:
                results.append(InstallResult(
                    platform=p.name,
                    config_file=p.config_path,
                    action="skipped",
                    note="already installed (use --force to overwrite)",
                ))
                continue
            new_text = _replace_rtt_section(existing, block) if _has_rtt_section(existing) else existing.rstrip("\n") + "\n\n" + block
            config.write_text(new_text, encoding="utf-8")
            results.append(InstallResult(platform=p.name, config_file=p.config_path, action="updated"))
        else:
            config.parent.mkdir(parents=True, exist_ok=True)
            config.write_text(block, encoding="utf-8")
            results.append(InstallResult(platform=p.name, config_file=p.config_path, action="created"))

    return results


def uninstall(
    repo_root: str,
    platform_names: Optional[list[str]],
    remove_skeleton: bool = False,
) -> list[InstallResult]:
    root = Path(repo_root)
    results: list[InstallResult] = []

    platforms = (
        [PLATFORM_BY_NAME[n] for n in platform_names if n in PLATFORM_BY_NAME]
        if platform_names
        else PLATFORMS
    )

    for p in platforms:
        config = root / p.config_path
        if not config.exists():
            continue
        text = config.read_text(encoding="utf-8")
        if not _has_rtt_section(text):
            continue
        cleaned = _remove_rtt_section(text)
        if cleaned.strip():
            config.write_text(cleaned, encoding="utf-8")
        else:
            config.unlink()
        results.append(InstallResult(platform=p.name, config_file=p.config_path, action="updated"))

    if remove_skeleton:
        skel = root / ".rtt" / "context.txt"
        if skel.exists():
            skel.unlink()

    _remove_git_hook(root)
    return results


# ── git hook ──────────────────────────────────────────────────────────────────

_HOOK_START = "# rtt:start"
_HOOK_END   = "# rtt:end"

_HOOK_BODY = """\
# rtt:start - keep .rtt/context.txt current on every commit
_RTT=$(command -v rtt 2>/dev/null)
if [ -n "$_RTT" ]; then
    "$_RTT" update . 2>/dev/null && git add .rtt/context.txt 2>/dev/null
fi
# rtt:end
"""


def install_git_hook(repo_root: str) -> str:
    """Install a pre-commit hook that runs `rtt update` before every commit.

    Returns "created", "updated", or "skipped" (no .git dir).
    """
    hook_path = Path(repo_root) / ".git" / "hooks" / "pre-commit"
    if not (Path(repo_root) / ".git").is_dir():
        return "skipped"

    if hook_path.exists():
        existing = hook_path.read_text(encoding="utf-8")
        if _HOOK_START in existing:
            return "skipped"
        new_text = existing.rstrip("\n") + "\n\n" + _HOOK_BODY
        hook_path.write_text(new_text, encoding="utf-8")
        hook_path.chmod(0o755)
        return "updated"

    shebang = "#!/bin/sh\n"
    hook_path.write_text(shebang + _HOOK_BODY, encoding="utf-8")
    hook_path.chmod(0o755)
    return "created"


def _remove_git_hook(repo_root: Path):
    hook_path = repo_root / ".git" / "hooks" / "pre-commit"
    if not hook_path.exists():
        return
    text = hook_path.read_text(encoding="utf-8")
    if _HOOK_START not in text:
        return
    pattern = re.compile(
        re.escape(_HOOK_START) + r".*?" + re.escape(_HOOK_END) + r"\n?",
        re.DOTALL,
    )
    cleaned = pattern.sub("", text).strip()
    if cleaned and cleaned != "#!/bin/sh":
        hook_path.write_text(cleaned + "\n", encoding="utf-8")
    else:
        hook_path.unlink()
